let SomaFunc = require("./somar")
let SubFunc = require("./sub")
let DivFunc = require("./divisao")
let MultiFunc = require("./multi")
console.log(`O valor da soma é ${SomaFunc(1,2)}`)
console.log(`O valor da subtração é ${SubFunc(8,2)}`)
console.log(`O valor da divisão é ${DivFunc(25,5)}`)
console.log(`O valor da multiplicação é ${MultiFunc(3,4)}`)
